language: ruby
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0-preview2
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: qmxqNdreAdu1Z3F2V1yORYuEAJV/Se4Df8LeRJnDZEEKM9boREUNUatY7N0cwHeiN7vZnQDrtMgkhYCT7J0MVwbWahuTzow/wPbI4TesEExRHyzrkPqAsjHI1wqySlkJ3kUAQpZs4vtr0kYTotHiqXlxmUaTADpPGUo3XrHyRIE=
sudo: false
